---
ansible_user: ilker
env_vars_mapping:
  DOMAINNAME:
    item: "Homeserver.nas"
    field: "DOMAINNAME"
  FILESTASH_ADMIN_PASSWORD_BCRYPT:
    item: "filestash.nas"
    field: "FILESTASH_ADMIN_PASSWORD_BCRYPT"
  VERSITYGW_ROOT_ACCESS_KEY:
    item: "s3-ui.nas"
    field: "username"
  VERSITYGW_ROOT_SECRET_KEY:
    item: "s3-ui.nas"
    field: "password"
