env_vars_mapping:
  ARCANE_AGENT_TOKEN:
    item: "Homeserver.rpi3"
    field: "ARCANE_AGENT_TOKEN"
  DIR_HARDDISKROOT:
    item: "Homeserver.rpi3"
    field: "DIR_HARDDISKROOT"
  DOMAINNAME:
    item: "Homeserver.rpi3"
    field: "DOMAINNAME"
