dev_devices:
  hosts:
    l13:
      ansible_host: 192.168.2.5
    gpu_coding:
      ansible_host: 192.168.2.21

lxcs:
  hosts:
    gpu_nvidia:
      ansible_host: 192.168.2.19
    lxc1:
      ansible_host: 192.168.2.20
    gpu_coding:
      ansible_host: 192.168.2.21
    nas:
      ansible_host: 192.168.2.23

rpis:
  hosts:
    rpi0:
      ansible_host: 192.168.2.12
    rpi1:
      ansible_host: 192.168.2.13
    rpi2:
      ansible_host: 192.168.2.14
    rpi3:
      ansible_host: 192.168.2.15

homeserver:
  hosts:
    gpu:
      ansible_host: 100.64.0.9
      local_static_ip: 192.168.2.9
    gpu_nvidia:
      ansible_host: 100.64.0.19
      local_static_ip: 192.168.2.19
    gpu_coding:
      ansible_host: 100.64.0.21
      local_static_ip: 192.168.2.21
    nas:
      ansible_host: 100.64.0.23
      local_static_ip: 192.168.2.23
    remoteserver:
      ansible_host: 100.64.0.1
      local_static_ip: 100.64.0.1
      user_name: ubuntu
    rpi0:
      ansible_host: 100.64.0.12
      local_static_ip: 192.168.2.12
    rpi1:
      ansible_host: 100.64.0.13
      local_static_ip: 192.168.2.13
    # rpi2:
    #   ansible_host: 100.64.0.14
    #   local_static_ip: 192.168.2.14
    # rpi3:
    #   ansible_host: 100.64.0.15
    #   local_static_ip: 192.168.2.15
