dev_devices:
  hosts:
    l13:
      ansible_host: 192.168.2.5
    gpu_coding:
      ansible_host: 192.168.2.21

lxcs:
  hosts:
    gpu_nvidia:
      ansible_host: 192.168.2.19
    lxc1:
      ansible_host: 192.168.2.20
    gpu_coding:
      ansible_host: 192.168.2.21

rpis:
  hosts:
    rpi0:
      ansible_host: 192.168.2.12
    rpi1:
      ansible_host: 192.168.2.13
    rpi2:
      ansible_host: 192.168.2.14
    rpi3:
      ansible_host: 192.168.2.15

homeserver:
  hosts:
    gpu:
      ansible_host: 100.64.0.19
      local_static_ip: 192.168.2.9
    gpu_nvidia:
      ansible_host: 192.168.2.19
      local_static_ip: 192.168.2.19
    remoteserver:
      ansible_host: 100.64.0.4
      local_static_ip: 100.64.0.4
      user_name: ubuntu
    rpi0:
      ansible_host: 100.64.0.17
      local_static_ip: 192.168.2.12
    rpi1:
      ansible_host: 100.64.0.10
      local_static_ip: 192.168.2.13
    # rpi2:
    #   ansible_host: 100.64.0.7
    #   local_static_ip: 192.168.2.14
    # rpi3:
    #   ansible_host: 100.64.0.7
    #   local_static_ip: 192.168.2.15
