---
homeserver_docker_manage_action: ""
homeserver_docker_manage_script_path: "{{ repo_path }}/scripts/docker-manage.sh"
homeserver_docker_manage_actions:
  down: {}
  prune: {}
  pull: {}
  restart: {}
  update: {}
  up: {}
