---
- name: Setup Debian LXC Hosts
  hosts: lxcs
  become: true
  vars:
    ansible_user: root

  roles:
    - role: common
    - role: docker_install
    - role: dotfiles_shell

- name: Setup Debian RPI Hosts
  hosts: rpis
  become: true

  roles:
    - role: common
    - role: docker_install
    - role: dotfiles_shell
